<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_Item</name>
   <tag></tag>
   <elementGuidId>e5e695cc-051a-4dec-afe4-56cb10a98b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cart_info_table']/thead/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Item&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2037b0fb-4678-44b1-b29e-247f05c0bced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5ecfe7cb-f393-4353-9e79-b2e50e92ebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Item</value>
      <webElementGuid>facd2edf-fca7-43a0-9f9c-69e8a05f41cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_info_table&quot;)/thead[1]/tr[@class=&quot;cart_menu&quot;]/td[@class=&quot;image&quot;]</value>
      <webElementGuid>7fa3cfbb-f846-4cfe-8304-84f6498ade33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cart_info_table']/thead/tr/td</value>
      <webElementGuid>ddb09441-037a-4a58-b869-88c343d2092a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue On Cart'])[1]/following::td[1]</value>
      <webElementGuid>9ad93a75-4a0b-4eae-af94-11cb24865497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register / Login'])[1]/following::td[1]</value>
      <webElementGuid>97946667-a900-4610-938b-741d29a96c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::td[1]</value>
      <webElementGuid>62669ee6-863d-4e54-a689-2de363b4565a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/preceding::td[2]</value>
      <webElementGuid>561ed165-10f2-42c6-a237-81c895ec6cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Item']/parent::*</value>
      <webElementGuid>2156b0a7-ec64-4d1a-89ee-8cb2abfe84ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>54f0a90e-3a80-49bb-b17c-9e7ef58edac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Item' or . = 'Item')]</value>
      <webElementGuid>b907f6c1-072d-4712-84bf-3ef4b2ed7b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
