<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , aswift_2, , ))_aswift_2</name>
   <tag></tag>
   <elementGuidId>9a44940d-b384-418b-94f7-894ecf0f446a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='aswift_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;aswift_2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>75aa3828-2a30-4a8d-8c06-37331ad7bab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aswift_2</value>
      <webElementGuid>cd770833-c5fb-40fc-956c-503e50732f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aswift_2</value>
      <webElementGuid>71272b25-b0c5-4338-a3f1-890ab7eface4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>21d6911f-452f-480d-b6a7-751545cb1b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc174ea5-35d9-4980-aa22-33f87e975a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d564ae6-f6be-463f-aa6a-cfa15bf10243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>329e532d-f6f2-484d-a27d-450dce383aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a82c6b8e-859c-4115-89e4-6d376fd6b803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f212c789-2cd4-4228-a2c3-01228a719e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e59dd728-0ebd-4e32-ab07-c486cb8c1f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a1ed19f9-4633-4d69-bac6-149a0b6339e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>attribution-reporting; run-ad-auction</value>
      <webElementGuid>2b87abf1-7b71-4f7b-b25e-af59e5a9bba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://googleads.g.doubleclick.net/pagead/html/r20260824/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-1677597403311019&amp;fa=8&amp;ifi=3&amp;uci=a!3</value>
      <webElementGuid>c34f2953-59c6-432d-9bdb-8e6b4b10d972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>a!3</value>
      <webElementGuid>cd58b014-04d9-47ba-9491-655bf148948e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eec8c3cf-f594-4c18-8cf0-327a4be44dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>7fb72aee-a771-4a19-8c6a-4e7e65b7ccfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>af31decd-30a5-4ae3-94a2-2a5138a15264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-query-id</name>
      <type>Main</type>
      <value>CN-F7qqZu5YDFTyW6QUdf-YeCQ</value>
      <webElementGuid>13326a2a-dd71-4979-a3fb-34df25a006b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf72f36f-65ec-48b4-92fd-a58d7d710903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_2&quot;)</value>
      <webElementGuid>5da502f4-d93d-44cc-a8fb-83faaa29c1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='aswift_2']</value>
      <webElementGuid>0e38cf70-ca4b-4c6b-b318-69e5e4a8700c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_2_host']/iframe</value>
      <webElementGuid>55c5b1d9-9fda-4304-8e10-cf6a0e9c92bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/ins/div/iframe</value>
      <webElementGuid>ef532cf3-d164-42d6-8496-d8fa1e752566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'aswift_2' and @name = 'aswift_2' and @src = 'https://googleads.g.doubleclick.net/pagead/html/r20260824/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-1677597403311019&amp;fa=8&amp;ifi=3&amp;uci=a!3' and @title = 'Advertisement']</value>
      <webElementGuid>5f0093cb-cca6-4bd8-92e7-4dc3c87e7872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
