<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , aswift_3, , ))_aswift_3</name>
   <tag></tag>
   <elementGuidId>ba55961d-0e96-4a33-922d-f090287ebdd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='aswift_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;aswift_3&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9f6eb921-88de-4ac9-aa23-24f028ba39f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aswift_3</value>
      <webElementGuid>5820f559-3e9e-497c-869b-d5c2e39cd70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aswift_3</value>
      <webElementGuid>310db859-17b2-43db-a0e5-d48bd38498d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>08266153-8567-44e8-8e60-92a20baf2025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c16aaf92-b6c0-4a74-94ef-3e1fdfe63267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>218ffeaf-a7d1-412f-b110-e9a7a8f3fa03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9a62c3d-dfd6-42a5-bace-112ef9630051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>55fc90d2-ec04-4be3-b341-25b591cac8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9300ce72-e095-4eb0-84df-21ee9e1c2205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0219a1a-45a9-41d9-8304-d69c594fcf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cc9d9505-24e2-4b44-bb8a-46aa0114b5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>attribution-reporting; run-ad-auction</value>
      <webElementGuid>78709d21-6aa3-4a69-b238-c8729280f644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://googleads.g.doubleclick.net/pagead/html/r20260824/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-1677597403311019&amp;fa=8&amp;ifi=4&amp;uci=a!4</value>
      <webElementGuid>bae8f605-449e-4e76-a2db-396e667e9454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>a!4</value>
      <webElementGuid>b5e39d8b-c49d-40bc-881c-a35f93301a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da77ad61-4d4d-425d-8d29-42557b42f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>8b1b9581-26c2-403c-9ea1-290572095525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>0d9dfc62-187d-4de0-994a-a52941119a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-query-id</name>
      <type>Main</type>
      <value>CI2B-9uTu5YDFQFMnQkdIg8QwQ</value>
      <webElementGuid>88fd5ae2-6377-41cc-acf0-d71a8a4b4d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa52f1a5-d460-48b7-ba5b-5f1764dfa718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_3&quot;)</value>
      <webElementGuid>3cbaed15-f72e-4e40-905f-582cabdfa758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='aswift_3']</value>
      <webElementGuid>bde89c52-c06a-4d3a-94fc-c212bd9074d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_3_host']/iframe</value>
      <webElementGuid>1a0cd4e7-c5ac-4f8d-81a2-018053a717af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/ins/div/iframe</value>
      <webElementGuid>81e01fb1-578e-4e85-b932-f31e93e4a412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'aswift_3' and @name = 'aswift_3' and @src = 'https://googleads.g.doubleclick.net/pagead/html/r20260824/r20190131/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-1677597403311019&amp;fa=8&amp;ifi=4&amp;uci=a!4' and @title = 'Advertisement']</value>
      <webElementGuid>2b783176-eaa1-499f-9e5f-950f28e8b537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
