<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscription_adpub-drawer-root-Details-245</name>
   <tag></tag>
   <elementGuidId>cfe1db9f-553c-4d0c-a87d-f534dcd2b599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.adpub-drawer-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.adpub-drawer-root</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6df110c-a9f8-402e-9f2f-67b5f8312e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>adpub-drawer-root</value>
      <webElementGuid>d249a970-1c00-4a10-b7ff-1e3886285f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/div[@class=&quot;adpub-drawer-root&quot;]</value>
      <webElementGuid>5642813f-efb7-4dec-8223-ff5e5e592421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/div</value>
      <webElementGuid>33833c6b-23ad-42af-8774-bf617ee87d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
