<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hd-modal-background-ils-245-e34</name>
   <tag></tag>
   <elementGuidId>2317f2e8-66a8-4c86-85a5-306dbc7df581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hd-drawer-container']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hd-modal-background</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ea7ca2e-9ccd-4af2-95d6-8d5c12150475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hd-modal-background</value>
      <webElementGuid>a5b7f6f2-d3d8-472e-bd2d-4c3a7d342330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;hd-drawer-container&quot;]/div[@id=&quot;hd-modal-background&quot;]</value>
      <webElementGuid>9fb2ed42-7210-4ae8-9975-2aa6939baf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Product Detail_Page/div_Subscription_adpub-drawer-root-Details-245</value>
      <webElementGuid>068624ca-31ef-48a6-b3f8-cea54dd9914d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1fa0e4c-75a4-462a-88ef-4b0a49c6de94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hd-drawer-container']/div</value>
      <webElementGuid>5ee5a231-d18b-48a2-afe4-cfda67bdebaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hd-modal-background']</value>
      <webElementGuid>cbb3670c-3b46-4442-b1c1-efbfe995b98a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
