<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up for our newsletter_optin</name>
   <tag></tag>
   <elementGuidId>4f5d1222-df3f-4566-8ab3-d175f2ec71ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='optin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Receive special offers from our partners!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11bbf115-5ce7-46e1-8b0e-e4f39c346ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>748a44af-7965-4907-bb69-64d0c0864ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optin</value>
      <webElementGuid>5142f243-8fd4-4604-9ac4-76ad7f51254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optin</value>
      <webElementGuid>2cd5fa45-2f8a-4fda-8778-47ee19f64ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0a4c09c4-644b-42cc-9034-460e97f6f41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optin&quot;)</value>
      <webElementGuid>cd382622-6fd8-47bc-8c76-b0dd9306b131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='optin']</value>
      <webElementGuid>1349b6d2-bac5-49c9-af78-cc974241a89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-optin']/span/input</value>
      <webElementGuid>5fd60375-7de7-42fe-8761-b06bb64b9a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/span/input</value>
      <webElementGuid>0f3e69de-23ac-4b6c-ae55-c9648d62c682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'optin' and @id = 'optin']</value>
      <webElementGuid>80792fe5-540d-41e7-9436-a11f38764a16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
