<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mobile_number</name>
   <tag></tag>
   <elementGuidId>349d5b33-8a4b-4ec8-a3bc-22e22ea52d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mobile Number *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2266a0d1-4cf0-482b-a0ea-de4c1c1c7e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0e22728-d756-430e-9e58-becf9a797be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>34ba5ba2-daaa-4928-ac95-cd994f3ef5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43b8feb3-6b9e-437e-b39a-c3863fa09762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>c6f0133f-7b5d-4a2b-886e-7293c099c60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>46589d90-330b-4a28-b185-3bac3bce1cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile_number&quot;)</value>
      <webElementGuid>ed3b0505-7765-42a2-8913-6fffe6d4ddbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile_number']</value>
      <webElementGuid>b356b279-4f74-4214-a370-79d15cb9b0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[10]/input</value>
      <webElementGuid>5eba19b9-fcff-4dbe-b9db-2dcf63405cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/input</value>
      <webElementGuid>129b3984-bbc6-444e-a22c-b7fd093f5bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mobile_number' and @id = 'mobile_number']</value>
      <webElementGuid>25d36648-6188-44b2-848b-2a92039aea64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
